kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: aia-behovsvurdering
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  ingresses:
    - https://aia-behovsvurdering.intern.dev.nav.no
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 60
  port: 8080
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 60
  replicas:
    min: 1
    max: 1
