name: Build, push, and deploy

on:
  push:
    branches:
      - main
      - dev/**

jobs:
  test-storybook:
    name:  Tester storybook
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '22.15.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@navikt'

      - name: 'Install dependencies'
        run: npm install --no-save --no-audit --prefer-offline --ignore-scripts --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Run tests'
        run: 'npm run test:ci'
       
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build storybook-static
        run: npm run build:storybook

      - name: Run test-storybook
        run: npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"

  build-cdn:
    name:  Build and upload to CDN
    needs: test-storybook
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    outputs:
      upload_url: ${{ steps.extract-manifest-url.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '22.15.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@navikt'

      - name: 'Install dependencies'
        run: 'npm ci'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Build cdn'
        run: 'NODE_ENV=production npm run build:cdn'

      - name: cdn-upload-js
        id: cdn-upload-js
        uses: nais/deploy/actions/cdn-upload/v2@master
        with:
          team: paw
          source: ./dist/
          destination: '/aia-behovsvurdering/'
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: "Extract manifest url"
        id: extract-manifest-url
        run: |
          files="${{ steps.cdn-upload-js.outputs.uploaded }}"
          first_file=$(echo $files | cut -d',' -f1)
          echo "upload_url=https://cdn.nav.no/$first_file" >> $GITHUB_OUTPUT    


  build-storybook:
    name: Build and upload storybook to nais
    needs: test-storybook
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '22.15.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@navikt'

      - name: 'Install dependencies'
        run: 'npm ci'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: 'Build storybook'
        run: 'npm run build:storybook'

      - name: docker-build-push
        id: docker-build-push
        uses: nais/docker-build-push@v0
        with:
          team: paw
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  update-manifest-dev-gcp:
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@main
    needs: build-cdn
    with:
      cluster: dev-gcp
      id: "aia-behovsvurdering"
      url: ${{needs.build-cdn.outputs.upload_url}}
      commitmsg: ${{ github.event.head_commit.message}}
    secrets: inherit

  update-manifest-prod-gcp:
    if: github.ref == 'refs/heads/main'
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@main
    needs: build-cdn
    with:
      cluster: prod-gcp
      id: "aia-behovsvurdering"
      url: ${{needs.build-cdn.outputs.upload_url}}
      commitmsg: ${{ github.event.head_commit.message}}
    secrets: inherit

  deploy-dev:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
    name: Deploy til dev
    permissions:
      contents: "read"
      id-token: "write"
    needs: build-storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          VAR: image=${{ needs.build-storybook.outputs.image }}


